from .ContactoViews import *
from .EstatusProveedorViews import *
from .LicitacionViews import *
from .LocalidadViews import *
from .MonedaViews import *
from .OrganismoViews import *
from .PaisViews import *
from .ProveedorViews import *
from .TipoContactoViews import *
from .EJecutivoViews import *