# Generated by Django 3.1.7 on 2021-06-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_auto_20210602_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estadoprovedorlicitacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='licitacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organismo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedorestatusproveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedorlicitacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rolejecutivo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipocontacto',
            options={'managed': True},
        ),
    ]
