# Generated by Django 3.1.7 on 2021-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_auto_20210602_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
