# Generated by Django 3.1.7 on 2021-06-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_auto_20210602_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivo',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
